### ISSUE TITLE
How to use translations in attributes?

### ISSUE THREAD

**Issue by Adiconquerors** [jetstreamlabs/zora#84]
Its excellent package which works well.

Is there a way to use translations in attributes like **placeholder** etc?

How to use this for laravel error messages?

Thanks.

**Comment by digvijayad** [comment]
> Is there a way to use translations in attributes like placeholder etc?

Yes, checkout the #82, I have updated the readme with some examples. But here is snippet from the pr.
```php
// lang/en/messages.php
return [
    'welcome' => 'Welcome, :name',
]
```
```js
// Dashbaord.js
__("messages.welcome", {"name": "Zora"});  // Welcome, Zora
```
I hope that's what you mean. If you are asking whether you can translate the attribute value, ex: the name 'Zora' in `__("messages.welcome", {"name": "Zora"});  // Welcome, Zora` then perhaps you can add a separate translation for the placeholder, and add it to the main translation. (NOT TESTED)
```php
// lang/en/messages.php
return [
    'welcome' => 'Welcome, :name',
    'Zora' => 'Zora.js'
]
```
```js
// Dashbaord.js
const zora_tr = __("Zora");
__("messages.welcome", {"name": zora_tr });  // Welcome, Zora
```

**Comment by Adiconquerors** [comment]
Hi digvijayad,

Thanks for detailed answer. We achieved this in following way:

> // lang/en/messages.php
> return [
>     'welcome' => 'Welcome, :name',
>     'Zora' => 'Zora.js'
> ]

> // Dashbaord.js
> `import { trans } from 'zora-js';
> import { Zora } from '../../../js/zora';
> 
>  function useTrans(key, replace) {
>             return trans(key, replace, Zora);
>         }
> 
>  useTrans('messages.welcome')`
